main:
  routes:
    - src:
        path:
          - /adm-svr/*
          - /dtw-svr/*
          - /equ-svr/*
          - /erp-svr/*
          - /kno-svr/*
          - /oss-svr/*
          - /msg-svr/*
          - /oa-svr/*
          - /igt-svr/*
          - /sms-svr/*
          - /prod-svr/*
      dst:
        host: gateway_svr
        port: 19090
        client:
          logActivity: true
        filters:
          auth: ''
    - src:
        path: /ttyd/*
      dst:
        host: 127.0.0.1
        port: 7681
        client:
          logActivity: true
        request:
          headers:
            Host: '127.0.0.1:7681'
        proxyInterceptors:
          pathPrefixReplace: /ttyd
          redirect:
            locationPrefix: /ttyd
    # Consul
    - src:
        path: /consul/*
      dst:
        host: consul
        port: 8500
        pathPrefixReplace: /consul
        filters:
          redirect:
            locationPrefix: /consul
          htmlReplace:
            - '"/ui/:"/consul/ui/'
            - '/v1/:/consul/v1/'
    # Kibana
    - src:
        path: /kibana/*
      dst:
        host: zlby-dev
        port: 40185
        pathPrefixReplace: /kibana
        filters:
          redirect:
            locationPrefix: /kibana
          htmlReplace:
            - srcPath: ^/login
              replacement:
                - 'href="/:href="/kibana/'
                - 'src="/:src="/kibana/'
                - "url\\('/:url\\('/kibana/"
                - '/translations/en.json:/kibana/translations/en.json'
                - '&quot;/50d89958910a:&quot;/kibana/50d89958910a'
            - srcPath: bootstrap-anonymous.js$
              replacement:
                - '/50d89958910a:/kibana/50d89958910a'
            - srcPath: security.plugin.js$
              replacement:
                - '/internal/security/me:/kibana/internal/security/me'
            - srcPath: core.entry.js$
              replacement:
                - '/api/core/capabilities:/kibana/api/core/capabilities'
    # 中控
    - src:
        path: /so/*
      dst:
        host: 192.168.53.11
        port: 8080
        pathPrefixReplace: /so
        filters:
          redirect:
            locationPrefix: /so
          htmlBase: /so
          htmlReplace:
            - srcPath: ^/$
              replacement:
                - '"/login:"/so/login'
                - '"/inter-api:"/so/inter-api'
            - srcPath: index_6041d837d0004d9f6129.js$
              replacement:
                - '"/inter-api:"/so/inter-api'
                - '"/api:"/so/api'
            - srcPath: ^/login/$
              replacement:
                - '"/login:"/so/login'
            - srcPath: index_7dac2c75bf4708f4b130.js$
              replacement:
#                - '"/login:"/so/login'
                - '"/inter-api:"/so/inter-api'
                - '"/api:"/so/api'
            - srcPath: global_setting_loginImages$
              replacement:
                - '"/api:"/so/api'
                - '"/systemconfig:"/so/systemconfig'
    # 中控
    - src:
        path:
          - /login/*
          - /inter-api/*
#          - /api/config/download/*
#          - /systemconfig/*
      dst:
        host: 192.168.53.11
        port: 8080

jwt:
  keyStore:
    # keytool -genkeypair -keystore keystore.pfx -storepass xxxxxxxx -keyalg EC -groupname secp521r1 -alias ES512 -keypass xxxxxxxx -sigalg SHA512withECDSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
    type: PKCS12
    path: config/keystore.pfx
    password: xxxxxxxx
  jwtOptions:
    # JWT签名算法
    algorithm: ES512
    # 签发者
    issuer: zbz
    # 超时时间(单位秒)
    expires: 1800

web:
  config:
    globalRouteHandlers:
      auth:
        admSvrHost: gateway_svr
        admSvrPort: 19090
    # 是否打印服务器监听日志
    isLogging: true
    # 跨域
    isCors: true
    server:
      port: 19080
      logActivity: true
      perMessageWebSocketCompressionSupported: false
      compressors:
        - gzip
        - brotli
        - deflate
        - snappy
        - zstd
