main:
  routes:
    - src:
        path:
          - /adm-svr/*
          - /dtw-svr/*
          - /equ-svr/*
          - /erp-svr/*
          - /kno-svr/*
          - /oss-svr/*
          - /msg-svr/*
          - /oa-svr/*
          - /igt-svr/*
          - /sms-svr/*
          - /prod-svr/*
      dst:
        host: gateway_svr
        port: 19090
        client:
          logActivity: true
        filters:
          admAuth: ''
    # 微信校验文件
    - src:
        path: /c6jZsGGRyD.txt
      dst:
        host: gatex02_svr
        port: 19080
        pathReplace: /admin-web/c6jZsGGRyD.txt
    - src:
        path: /ttyd/*
      dst:
        host: 127.0.0.1
        port: 7681
        client:
          logActivity: true
        request:
          headers:
            Host: '127.0.0.1:7681'
        pathPrefixReplace: /ttyd
        filters:
          redirect:
            locationPrefix: /ttyd
    # Consul
    - src:
        path: /consul/*
      dst:
        host: consul
        port: 8500
        pathPrefixReplace: /consul
        filters:
          redirect:
            locationPrefix: /consul
          htmlReplace:
            - '"/ui/:"/consul/ui/'
            - '/v1/:/consul/v1/'
    # Kibana
    - src:
        path: /kibana/*
      dst:
        host: zlby-dev
        port: 40185
        pathPrefixReplace: /kibana
        filters:
          redirect:
            locationPrefix: /kibana
          htmlReplace:
            - srcPath: ^/login
              replacement:
                - 'href="/:href="/kibana/'
                - 'src="/:src="/kibana/'
                - "url\\('/:url\\('/kibana/"
                - '/translations/en.json:/kibana/translations/en.json'
                - '&quot;/50d89958910a:&quot;/kibana/50d89958910a'
            - srcPath: bootstrap-anonymous.js$
              replacement:
                - '/50d89958910a:/kibana/50d89958910a'
            - srcPath: security.plugin.js$
              replacement:
                - '/internal/security/me:/kibana/internal/security/me'
            - srcPath: core.entry.js$
              replacement:
                - '/api/core/capabilities:/kibana/api/core/capabilities'
