<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>gatex</artifactId>
        <groupId>io.github.myvertx</groupId>
        <version>1.3.42</version>
    </parent>

    <artifactId>gatex-util</artifactId>
    <description>基于vert.x构建的网关的工具</description>

    <properties>
        <wheel.version>3.8.60</wheel.version>
        <vertx.version>4.5.18</vertx.version>
        <guice.version>7.0.0</guice.version>
        <guava.version>33.0.0-jre</guava.version>
        <janino.version>3.1.12</janino.version>
        <drools.version>10.0.0</drools.version>
        <pulsar.version>3.3.7</pulsar.version>
        <commons-lang3.version>3.14.0</commons-lang3.version>
        <slf4j.version>2.0.7</slf4j.version>
        <logback.version>1.5.16</logback.version>
        <junit.version>5.12.0</junit.version>
        <lombok.version>1.18.36</lombok.version>
    </properties>

    <url>https://github.com/myvertx/gatex</url>
    <developers>
        <developer>
            <name>zbz</name>
            <email>nnzbz@qq.com</email>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://www.opensource.org/licenses/mit-license.php</url>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:https://github.com/myvertx/gatex</connection>
        <developerConnection>scm:git:https://github.com/myvertx/gatex.git</developerConnection>
        <url>https://github.com/myvertx/gatex.git</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>io.github.myvertx</groupId>
            <artifactId>gatex-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.rebue.wheel</groupId>
            <artifactId>wheel-core</artifactId>
            <version>${wheel.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.rebue.wheel</groupId>
            <artifactId>wheel-vertx</artifactId>
            <version>${wheel.version}</version>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-http-proxy</artifactId>
            <version>${vertx.version}</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <version>${vertx.version}</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web-client</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <!-- 依赖注入 -->
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>${guice.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>

        <dependency>
            <groupId>org.kie</groupId>
            <artifactId>kie-api</artifactId>
            <version>${drools.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- logback配置使用if需要 -->
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
            <version>${janino.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- 代码生成 -->
        <!-- lombok的依赖必须在最前面，否则其它生成器在没有lombok生成代码时，有可能会失效 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.kie</groupId>
                <artifactId>kie-maven-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
</project>