<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.myvertx</groupId>
        <artifactId>gatex</artifactId>
        <version>1.3.38</version>
    </parent>
    <artifactId>gatex-api</artifactId>
    <description>基于vert.x构建的网关的Java API接口</description>

    <properties>
        <wheel.version>3.5.44</wheel.version>
        <vertx.version>4.5.9</vertx.version>
        <guice.version>7.0.0</guice.version>
        <guava.version>33.0.0-jre</guava.version>
        <lombok.version>1.18.32</lombok.version>
    </properties>

    <url>https://github.com/myvertx/gatex</url>
    <developers>
        <developer>
            <name>zbz</name>
            <email>nnzbz@qq.com</email>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://www.opensource.org/licenses/mit-license.php</url>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:https://github.com/myvertx/gatex</connection>
        <developerConnection>scm:git:https://github.com/myvertx/gatex.git</developerConnection>
        <url>https://github.com/myvertx/gatex.git</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.github.rebue.wheel</groupId>
            <artifactId>wheel-vertx</artifactId>
            <version>${wheel.version}</version>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <version>${vertx.version}</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-http-proxy</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <!-- 依赖注入 -->
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>${guice.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
    </dependencies>
</project>